<?php
/**
 * @file
 * ghel_translation.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function ghel_translation_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'comment-comment_node_ghel_translation-comment_body'.
  $field_instances['comment-comment_node_ghel_translation-comment_body'] = array(
    'bundle' => 'comment_node_ghel_translation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'comment',
    'field_name' => 'comment_body',
    'label' => 'Comment',
    'required' => TRUE,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 0,
    ),
  );

  // Exported field_instance: 'node-ghel_translation-field_ghel_language'.
  $field_instances['node-ghel_translation-field_ghel_language'] = array(
    'bundle' => 'ghel_translation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 4,
      ),
      'full' => array(
        'label' => 'inline',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_plain',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'inline',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_plain',
        'weight' => 2,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_ghel_language',
    'formblock_expose' => 0,
    'label' => 'Language',
    'required' => 1,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => -4,
    ),
  );

  // Exported field_instance:
  // 'node-ghel_translation-field_ghel_promotional_text'.
  $field_instances['node-ghel_translation-field_ghel_promotional_text'] = array(
    'bundle' => 'ghel_translation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 10,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_ghel_promotional_text',
    'formblock_expose' => 0,
    'label' => 'Promotional Text',
    'required' => 0,
    'settings' => array(
      'display_summary' => 0,
      'entity_translation_sync' => FALSE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => -1,
    ),
  );

  // Exported field_instance: 'node-ghel_translation-field_ghel_trans_file'.
  $field_instances['node-ghel_translation-field_ghel_trans_file'] = array(
    'bundle' => 'ghel_translation',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'file',
        'settings' => array(),
        'type' => 'file_default',
        'weight' => 2,
      ),
      'full' => array(
        'label' => 'inline',
        'module' => 'file',
        'settings' => array(),
        'type' => 'file_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'file',
        'settings' => array(),
        'type' => 'file_default',
        'weight' => 3,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_ghel_trans_file',
    'formblock_expose' => 0,
    'label' => 'Translation',
    'required' => 0,
    'settings' => array(
      'description_field' => 0,
      'entity_translation_sync' => FALSE,
      'file_directory' => 'sites/default/files/translated-courses',
      'file_extensions' => 'txt pdf doc docx odt epub mobi',
      'max_filesize' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'file',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => 0,
        'insert_class' => '',
        'insert_default' => 'auto',
        'insert_styles' => array(
          'auto' => 'auto',
          'colorbox__extra_large_center' => 0,
          'colorbox__featured' => 0,
          'colorbox__large' => 0,
          'colorbox__large_center' => 0,
          'colorbox__large_left' => 0,
          'colorbox__large_right' => 0,
          'colorbox__linkit_thumb' => 0,
          'colorbox__medium' => 0,
          'colorbox__medium_center' => 0,
          'colorbox__medium_left' => 0,
          'colorbox__medium_right' => 0,
          'colorbox__teaser' => 0,
          'colorbox__thumbnail' => 0,
          'colorbox__user_profile' => 0,
          'icon_link' => 0,
          'image' => 0,
          'image_extra_large_center' => 0,
          'image_featured' => 0,
          'image_large' => 0,
          'image_large_center' => 0,
          'image_large_left' => 0,
          'image_large_right' => 0,
          'image_linkit_thumb' => 0,
          'image_medium' => 0,
          'image_medium_center' => 0,
          'image_medium_left' => 0,
          'image_medium_right' => 0,
          'image_teaser' => 0,
          'image_thumbnail' => 0,
          'image_user_profile' => 0,
          'link' => 0,
        ),
        'insert_width' => '',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'file_generic',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-ghel_translation-field_image'.
  $field_instances['node-ghel_translation-field_image'] = array(
    'bundle' => 'ghel_translation',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => 'medium',
        ),
        'type' => 'image',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => 'medium',
        ),
        'type' => 'image',
        'weight' => 8,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_image',
    'formblock_expose' => 0,
    'label' => 'Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'entity_translation_sync' => FALSE,
      'file_directory' => 'translation-images',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => 0,
        'insert_class' => '',
        'insert_default' => 'auto',
        'insert_styles' => array(
          'auto' => 'auto',
          'colorbox__extra_large_center' => 0,
          'colorbox__featured' => 0,
          'colorbox__large' => 0,
          'colorbox__large_center' => 0,
          'colorbox__large_left' => 0,
          'colorbox__large_right' => 0,
          'colorbox__linkit_thumb' => 0,
          'colorbox__medium' => 0,
          'colorbox__medium_center' => 0,
          'colorbox__medium_left' => 0,
          'colorbox__medium_right' => 0,
          'colorbox__teaser' => 0,
          'colorbox__thumbnail' => 0,
          'colorbox__user_profile' => 0,
          'icon_link' => 0,
          'image' => 0,
          'image_extra_large_center' => 0,
          'image_featured' => 0,
          'image_large' => 0,
          'image_large_center' => 0,
          'image_large_left' => 0,
          'image_large_right' => 0,
          'image_linkit_thumb' => 0,
          'image_medium' => 0,
          'image_medium_center' => 0,
          'image_medium_left' => 0,
          'image_medium_right' => 0,
          'image_teaser' => 0,
          'image_thumbnail' => 0,
          'image_user_profile' => 0,
          'link' => 0,
        ),
        'insert_width' => '',
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => -3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Comment');
  t('Image');
  t('Language');
  t('Promotional Text');
  t('Translation');

  return $field_instances;
}
