<?php
/**
 * @file
 * ghel_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function ghel_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Other',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '049d85ae-fb16-9f24-5552-bb5da2cbc931',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_occupation_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Mulitlateral',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1d57e43c-94a5-ddb4-6dd3-b93a2bfaa929',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'USG Agency - CDC',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3831097e-b4c4-3b84-1102-a17136cac793',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Other',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '38664022-5e53-0874-3104-f8d9eaa7c695',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Translations',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3da470b4-36d2-1154-a1c0-f82161be4845',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_faq_categories',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Announcement',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4c350404-52c1-6674-d975-7d2a43cdcd84',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_announcement_types',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Conference Announcement',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5dc75a2b-d92b-a6a4-4d0a-5c84419dd879',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_announcement_types',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Academic',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6d04380a-8315-a0c4-f1f6-93e75d734664',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_occupation_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'USG Agency - Peace Corps',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '73899c15-41bd-3dd4-35d3-0120cb46c5a1',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Course Development',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7c0bdabe-e143-e664-ddc8-bce9679302ea',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_faq_categories',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Learner Profile Highlight',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8ac88178-4112-88a4-cd40-c5df2f09c3e3',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_announcement_types',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'National Government',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9269415f-15c2-1a14-119b-f66252f2e0fc',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Programmatic',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '92d86690-549f-9574-61a8-67a556aa5c75',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_occupation_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'National/local non-governmental organization',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b2fb3f96-3cbb-7714-21f9-7d3734be028d',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Certificate Questions',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b649ce27-41b6-7ca4-513c-27e0656e995f',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_faq_categories',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'USG Agency - State',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bf9ebe62-33f7-cdf4-7105-f36205f4dceb',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Course Access',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c48a3cec-993a-e1d4-65a6-7e49647e2295',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_faq_categories',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Student',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'd0952a96-8ae9-fd54-b5de-8c21f820e78f',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_occupation_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Non-US based university',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd0e8b195-f0eb-bd24-ad2e-883cd7d43de8',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'USG Agency - Other',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dcd65dbc-b245-f414-5de6-8c1775d6b9e1',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'Clinical',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'eb17680d-8a15-e4e4-6d62-1fb723179b03',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_occupation_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'USG Agency - USAID',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f030fea7-5db3-43c4-a52c-575bd50804ea',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  $terms[] = array(
    'name' => 'International Non-governmental organization',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f496cfc2-34a7-1344-8df1-5eb1037cde69',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'ghel_organization_category',
    'epub_export_type' => 'taxonomy_term',
    'formblock_entity_type' => 'taxonomy_term',
    'lingotek' => array(
      'name' => 'DISABLED',
      'profile' => 'DISABLED',
    ),
  );
  return $terms;
}
